@startuml
top to bottom direction
(Ventilador [41]) --> (Mesa [20]) : L
(Ventilador [41]) --> (Presente [62]) : R
(Mesa [20]) --> (Rabo [10]) : L
(Mesa [20]) --> (Coelho [31]) : R
(Rabo [10]) --> (Dado [5]) : L
(Rabo [10]) --> (Sapato [15]) : R
(Dado [5]) --> (Dedo [2]) : L
(Dado [5]) --> (Tênis [8]) : R
(Dedo [2]) --> (Bebê [1]) : L
(Dedo [2]) --> (Batom [4]) : R
(Bebê [1]) --> (Anel [0]) : L
(Batom [4]) --> (Cama [3]) : L
(Tênis [8]) --> (Navio [6]) : L
(Tênis [8]) --> (Dente [9]) : R
(Navio [6]) --> (Terra [7]) : R
(Sapato [15]) --> (Caminhão [12]) : L
(Sapato [15]) --> (Lápis [18]) : R
(Caminhão [12]) --> (Faca [11]) : L
(Caminhão [12]) --> (Sapo [14]) : R
(Sapo [14]) --> (Fogo [13]) : L
(Lápis [18]) --> (Cabelo [16]) : L
(Lápis [18]) --> (Galinha [19]) : R
(Cabelo [16]) --> (Vaca [17]) : R
(Coelho [31]) --> (Sofá [25]) : L
(Coelho [31]) --> (Cachorro [36]) : R
(Sofá [25]) --> (Cavalo [22]) : L
(Sofá [25]) --> (Folha [28]) : R
(Cavalo [22]) --> (Gato [21]) : L
(Cavalo [22]) --> (Casa [24]) : R
(Casa [24]) --> (Bolsa [23]) : L
(Folha [28]) --> (Barriga [26]) : L
(Folha [28]) --> (Pastel [30]) : R
(Barriga [26]) --> (Calça [27]) : R
(Pastel [30]) --> (Chapéu [29]) : L
(Cachorro [36]) --> (Chinelo [33]) : L
(Cachorro [36]) --> (Relógio [39]) : R
(Chinelo [33]) --> (Língua [32]) : L
(Chinelo [33]) --> (Caixa [35]) : R
(Caixa [35]) --> (Beijo [34]) : L
(Relógio [39]) --> (Espelho [37]) : L
(Relógio [39]) --> (Porta [40]) : R
(Espelho [37]) --> (Nuvem [38]) : R
(Presente [62]) --> (Prato [51]) : L
(Presente [62]) --> (Escrever [73]) : R
(Prato [51]) --> (Jornal [46]) : L
(Prato [51]) --> (Soprar [57]) : R
(Jornal [46]) --> (Passarinho [43]) : L
(Jornal [46]) --> (Girafa [49]) : R
(Passarinho [43]) --> (Zero [42]) : L
(Passarinho [43]) --> (Nariz [45]) : R
(Nariz [45]) --> (Tesoura [44]) : L
(Girafa [49]) --> (Garfo [47]) : L
(Girafa [49]) --> (Brinco [50]) : R
(Garfo [47]) --> (Jacaré [48]) : R
(Soprar [57]) --> (Grama [54]) : L
(Soprar [57]) --> (Fralda [60]) : R
(Grama [54]) --> (Cobra [52]) : L
(Grama [54]) --> (Trem [56]) : R
(Cobra [52]) --> (Zebra [53]) : R
(Trem [56]) --> (Cruz [55]) : L
(Fralda [60]) --> (Placa [58]) : L
(Fralda [60]) --> (Refri [61]) : R
(Placa [58]) --> (Fruta [59]) : R
(Escrever [73]) --> (Gritar [67]) : L
(Escrever [73]) --> (Vidro [78]) : R
(Gritar [67]) --> (Chiclete [64]) : L
(Gritar [67]) --> (Plástico [70]) : R
(Chiclete [64]) --> (Livro [63]) : L
(Chiclete [64]) --> (Bicicleta [66]) : R
(Bicicleta [66]) --> (Chifre [65]) : L
(Plástico [70]) --> (Bruxa [68]) : L
(Plástico [70]) --> (Flor [72]) : R
(Bruxa [68]) --> (Letra [69]) : R
(Flor [72]) --> (Igreja [71]) : L
(Vidro [78]) --> (Magro [75]) : L
(Vidro [78]) --> (Floresta [81]) : R
(Magro [75]) --> (Dragão [74]) : L
(Magro [75]) --> (Pedra [77]) : R
(Pedra [77]) --> (Estrela [76]) : L
(Floresta [81]) --> (Microfone [79]) : L
(Floresta [81]) --> (Biblioteca [82]) : R
(Microfone [79]) --> (Colher [80]) : R
(Biblioteca [82]) --> (Travesseiro [83]) : R
@enduml
