@startuml
top to bottom direction
(Ventilador [41]) --> (Mesa [20]) : L
(Ventilador [41]) --> (Presente [62]) : R
(Mesa [20]) --> (Dente [9]) : L
(Mesa [20]) --> (Pastel [30]) : R
(Dente [9]) --> (Batom [4]) : L
(Dente [9]) --> (Sapo [14]) : R
(Batom [4]) --> (Bebê [1]) : L
(Batom [4]) --> (Navio [6]) : R
(Bebê [1]) --> (Anel [0]) : L
(Bebê [1]) --> (Dedo [2]) : R
(Dedo [2]) --> (Cama [3]) : R
(Navio [6]) --> (Dado [5]) : L
(Navio [6]) --> (Terra [7]) : R
(Terra [7]) --> (Tênis [8]) : R
(Sapo [14]) --> (Faca [11]) : L
(Sapo [14]) --> (Vaca [17]) : R
(Faca [11]) --> (Rabo [10]) : L
(Faca [11]) --> (Caminhão [12]) : R
(Caminhão [12]) --> (Fogo [13]) : R
(Vaca [17]) --> (Sapato [15]) : L
(Vaca [17]) --> (Lápis [18]) : R
(Sapato [15]) --> (Cabelo [16]) : R
(Lápis [18]) --> (Galinha [19]) : R
(Pastel [30]) --> (Sofá [25]) : L
(Pastel [30]) --> (Caixa [35]) : R
(Sofá [25]) --> (Cavalo [22]) : L
(Sofá [25]) --> (Calça [27]) : R
(Cavalo [22]) --> (Gato [21]) : L
(Cavalo [22]) --> (Bolsa [23]) : R
(Bolsa [23]) --> (Casa [24]) : R
(Calça [27]) --> (Barriga [26]) : L
(Calça [27]) --> (Folha [28]) : R
(Folha [28]) --> (Chapéu [29]) : R
(Caixa [35]) --> (Língua [32]) : L
(Caixa [35]) --> (Nuvem [38]) : R
(Língua [32]) --> (Coelho [31]) : L
(Língua [32]) --> (Chinelo [33]) : R
(Chinelo [33]) --> (Beijo [34]) : R
(Nuvem [38]) --> (Cachorro [36]) : L
(Nuvem [38]) --> (Relógio [39]) : R
(Cachorro [36]) --> (Espelho [37]) : R
(Relógio [39]) --> (Porta [40]) : R
(Presente [62]) --> (Prato [51]) : L
(Presente [62]) --> (Escrever [73]) : R
(Prato [51]) --> (Jornal [46]) : L
(Prato [51]) --> (Trem [56]) : R
(Jornal [46]) --> (Passarinho [43]) : L
(Jornal [46]) --> (Jacaré [48]) : R
(Passarinho [43]) --> (Zero [42]) : L
(Passarinho [43]) --> (Tesoura [44]) : R
(Tesoura [44]) --> (Nariz [45]) : R
(Jacaré [48]) --> (Garfo [47]) : L
(Jacaré [48]) --> (Girafa [49]) : R
(Girafa [49]) --> (Brinco [50]) : R
(Trem [56]) --> (Zebra [53]) : L
(Trem [56]) --> (Fruta [59]) : R
(Zebra [53]) --> (Cobra [52]) : L
(Zebra [53]) --> (Grama [54]) : R
(Grama [54]) --> (Cruz [55]) : R
(Fruta [59]) --> (Soprar [57]) : L
(Fruta [59]) --> (Fralda [60]) : R
(Soprar [57]) --> (Placa [58]) : R
(Fralda [60]) --> (Refri [61]) : R
(Escrever [73]) --> (Gritar [67]) : L
(Escrever [73]) --> (Vidro [78]) : R
(Gritar [67]) --> (Chiclete [64]) : L
(Gritar [67]) --> (Plástico [70]) : R
(Chiclete [64]) --> (Livro [63]) : L
(Chiclete [64]) --> (Chifre [65]) : R
(Chifre [65]) --> (Bicicleta [66]) : R
(Plástico [70]) --> (Bruxa [68]) : L
(Plástico [70]) --> (Igreja [71]) : R
(Bruxa [68]) --> (Letra [69]) : R
(Igreja [71]) --> (Flor [72]) : R
(Vidro [78]) --> (Magro [75]) : L
(Vidro [78]) --> (Floresta [81]) : R
(Magro [75]) --> (Dragão [74]) : L
(Magro [75]) --> (Estrela [76]) : R
(Estrela [76]) --> (Pedra [77]) : R
(Floresta [81]) --> (Microfone [79]) : L
(Floresta [81]) --> (Biblioteca [82]) : R
(Microfone [79]) --> (Colher [80]) : R
(Biblioteca [82]) --> (Travesseiro [83]) : R
@enduml
